services:
  - type: web
    name: Inventory-Retracement-Bar
    env: python
    plan: free
    region: frankfurt
    buildCommand: "pip install -r deploy-requirements.txt"
    startCommand: "gunicorn app:server"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0